pom.xml, src/main/resources/markdown/releases.md
Change the links to archive.apache.org page to direct links to downloads.apache.org. Also adjust words.
Please help on review :-)
cc @eolivelli
=> ZOOKEEPER-3746. Move the download page to downloads.apache.org

.asf.yaml
This trivial change adds the missing .asf.yaml file that ensures the
asf-site branch gets published to https://zookeeper.apache.org using ASF
publishing mechanisms when things are changed in the git branch.
This resolves the outstanding issue with this site's publishing that was
identified in the INFRA report at
https://infra-reports.apache.org/site-source/
=> Add missing .asf.yaml file to publish website

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxn.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxnFactory.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/NettyServerCnxnTest.java
- add new flag netty.server.earlyDropSecureConnectionHandshakes to turn on/off ZOOKEEPER-3682
- disable ZOOKEEPER-3682 by default
- add docs
- add tests for this patch and for ZOOKEEPER-3682
see https://issues.apache.org/jira/browse/ZOOKEEPER-4453 for more context
=> ZOOKEEPER-4453: NettyServerCnxnFactory: allow to configure the early TLS connection drop feature

owaspSuppressions.xml, pom.xml, zookeeper-server/src/main/java/org/apache/zookeeper/cli/AddAuthCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/AddWatchCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/CreateCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/DelQuotaCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/DeleteAllCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/DeleteCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/GetAclCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/GetAllChildrenNumberCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/GetCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/GetConfigCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/GetEphemeralsCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/ListQuotaCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/LsCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/ReconfigCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/RemoveWatchesCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/SetAclCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/SetCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/SetQuotaCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/StatCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/SyncCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/VersionCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/TxnLogToolkit.java
commons-cli 1.2 was released in 2009, time to upgrade it to the newest version (1.4). To avoid deprecation messages we have to upgrade the Java code too.
Author: Tamas Penzes <tamaas@cloudera.com>
Reviewers: Enrico Olivelli <eolivelli@apache.org>, Mate Szalay-Beko <symat@apache.org>
Closes #1463 from tamaashu/zookeeper-3941
(cherry picked from commit 492fd79b0c7845f1b7f3717632471d79660d1363)
=> ZOOKEEPER-3941: Upgrade commons-cli to 1.4

pom.xml
This PR aims to publish SBOM artifacts along with the other Apache projects.
- https://cwiki.apache.org/confluence/display/COMDEV/SBOM
Here is an article to give some context.
- https://www.activestate.com/blog/why-the-us-government-is-mandating-software-bill-of-materials-sbom/
Software Bill of Materials (SBOM) are additional artifacts containing the aggregate of all direct and transitive dependencies of a project. The US Government (based on NIST recommendations) currently accepts only the three most popular SBOM standards as valid, namely: [CycloneDX](https://cyclonedx.org/), [Software Identification (SWID) tag](https://csrc.nist.gov/projects/Software-Identification-SWID), [Software Package Data Exchange® (SPDX)](https://spdx.dev/).
We can use one of the Maven plugin, [CycloneDX maven …
=> ZOOKEEPER-4657: Publish SBOM artifacts

pom.xml, zookeeper-server/pom.xml, zookeeper-server/src/main/java/org/apache/zookeeper/common/ZKHostnameVerifier.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/ZKTrustManager.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/ZKTrustManagerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumCanonicalizeTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/StaticHostProviderTest.java
Some tests do not pass on latest JDK20 (and also in JDK19) because we are trying to mock InetAddress.
More context here
https://issues.apache.org/jira/browse/ZOOKEEPER-4647
Unfortunately upgrading Mockito doesn't help and so I had to add Burning Wave DNS tools on the classpath.
https://dev.to/jjbrt/how-to-configure-hostname-resolution-to-use-a-universal-custom-hostname-resolver-in-java-14p0
The tests that mock InetAddress now pass on JDK19 and JDK20 on my laptop
=> [ZOOKEEPER-4647] Tests don't pass on JDK20 because we try to mock InetAddress

zookeeper-server/src/main/java/org/apache/zookeeper/ZKWatchManager.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/PersistentRecursiveWatcherTest.java
Cause:
* Events are delivered to recursive watcher unconditionally.
* Client could receive `NodeChildrenChanged` due to child watcher on recursive watching node's descendants.
Changes: Filter out `NodeChildrenChanged` events for recursive watcher in client side.
=> ZOOKEEPER-4475: Fix NodeChildrenChanged delivered to recursive watcher

zookeeper-docs/src/main/resources/markdown/html/header.html, zookeeper-docs/src/main/resources/markdown/index.md, zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-docs/src/main/resources/markdown/zookeeperSnapshotAndRestore.md, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/AuthRequest.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/Command.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/CommandBase.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/Commands.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/GetCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/JettyAdminServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/PostCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/StreamOutputter.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/AuthenticationProvider.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/DigestAuthenticationProvider.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/IPAuthenticationProvider.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/WrappedAuthenticationProvider.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/X509AuthenticationProvider.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/admin/CommandAuthTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/admin/CommandsTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/admin/RestoreQuorumTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/admin/SnapshotAndRestoreCommandTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerTestBase.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/IPAuthTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ObserverMasterTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/X509AuthTest.java
Provide auth support including digest, x509 and IP for admin server commands.
Author: Li Wang [liwang@apple.com](mailto:liwang@apple.com)
=> ZOOKEEPER-4639: Provide auth support for admin server APIs

zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocketNetty.java, zookeeper-server/src/test/java/org/apache/zookeeper/ClientCnxnSocketTest.java
See [ZOOKEEPER-4296](https://issues.apache.org/jira/browse/ZOOKEEPER-4296) for more context.
What I've done here fixes (the symptoms of?) a problem that I have hit in the real world when using Solr's SolrZkClient. But I don't have enough knowledge of ZooKeeper's code to say whether there's a bigger issue in terms of how `ClientCnxnSocketNetty` is being used. What I do know is that `ClientCnxnSocketNIO` handled the same scenario without any apparent issue.
In any case getting NullPointerExceptions when closing something isn't helpful.
=> ZOOKEEPER-4296: Add null checks to ClientCnxnSocketNetty onClosing

.github/workflows/ci.yaml, .github/workflows/e2e.yaml, .github/workflows/manual.yaml
Proposing bumping the version of `actions/checkout` used in these GitHub Actions workflows to v3 - https://github.com/actions/checkout#checkout-v3
=> Bump actions/checkout to v3 in GitHub Actions workflows

.github/workflows/ci.yaml, .github/workflows/e2e.yaml, .github/workflows/manual.yaml
1. Run `apt update` before installing C deps to avoid 404.
2. Update actions version to avoid set-output deprecation warnings.
=> ZOOKEEPER-4679: Fix CI failure and warning 

bin/zkEnv.sh
Hi all,
When developing zookeeper, we often start or debug it by using the current source code instead of the built package. So it is good to add the classes about metrics providers to the classpath to avoid ClassNotFound exception. This ClassNotFound exception happens when we use the config `metricsProvider.className=org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider` to start zookeeper.
Thanks for taking the time to review.
Best Regards,
-- Guoxiong
=> [ZOOKEEPER-4671] Java classpath should contain libs about metrics providers

zookeeper-server/src/main/java/org/apache/zookeeper/server/SnapshotComparer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/SnapshotFormatter.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/SnapshotRecursiveSummary.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZKDatabase.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileSnap.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/CRCTest.java
FileSnap.deserialize is effectively a static method. Change it to a static method so that we don't need to do some `new FileSnap(null)` hacks for workaround calling this method.
a.k.a. pay back some tech debt.
=> ZOOKEEPER-4682. Make FileSnap.deserialize a static method

zookeeper-server/src/main/java/org/apache/zookeeper/Watcher.java, zookeeper-server/src/main/java/org/apache/zookeeper/ZKWatchManager.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/RemoveWatchesCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/DataTree.java, zookeeper-server/src/test/java/org/apache/zookeeper/RemoveWatchesTest.java
[ZOOKEEPER-4466][] supports different watch modes one same path, but there are no corresponding `WatcherType`s for persistent watches. Client has to resort to `WatcherType.Any` to remove them. This could accidently interrupt other watches.
This PR adds `WatcherType.Persistent` and `WatcherType.PersistentRecursive` to remove persistent watches individually.
Besides above, this pr bases on #1998.
[ZOOKEEPER-4466]: https://issues.apache.org/jira/browse/ZOOKEEPER-4466
=> ZOOKEEPER-4472: Remove persistent watches individually 

zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocketNetty.java, zookeeper-server/src/main/java/org/apache/zookeeper/client/FourLetterWordMain.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/SSLContextAndOptions.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/ZKConfig.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxnFactory.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/X509AuthenticationProvider.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/X509UtilTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumSSLTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ClientSSLTest.java
Proposed fix for FIPS-enablement, details have been discussed on the ticket and the mailing list.
Includes:
- Choose built-in `X509TrustManagerImpl` for trust manager if FIPS-mode is enabled,
- Turn-on hostname verification in Netty stack (client-server comm only),
- unit tests,
- code cleanup.
ps. JUnit 5 parameterized tests are a nightmare. What happened to the original impl...?
cc @eolivelli @symat @phunt @ctubbsii
=> ZOOKEEPER-4393 Problem to connect to zookeeper in FIPS mode

zookeeper-it/src/main/java/org/apache/zookeeper/server/watch/WatchBench.java, zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxn.java, zookeeper-server/src/main/java/org/apache/zookeeper/WatchedEvent.java, zookeeper-server/src/main/java/org/apache/zookeeper/Watcher.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/DataTree.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/DumbWatcher.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/NIOServerCnxn.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxn.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/watch/IWatchManager.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/watch/WatchManager.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/watch/WatchManagerOptimized.java, zookeeper-server/src/test/java/org/apache/zookeeper/ZKTestCase.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/RequestThrottlerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/persistence/FileTxnSnapLogMetricsTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/LearnerMetricsTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/watch/WatchManagerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/watch/WatcherCleanerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/PersistentRecursiveWatcherTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/TestUtils.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/UnsupportedAddWatcherTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/WatchedEventTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/WatcherFuncTest.java
With the recent addition of persistent watches, many doors have opened up to significantly more performant and intuitive local caches of remote state, but the actual implementation can be difficult because to cache data locally, one needs to execute the following steps:
1. Set the watch
2. Bootstrap the watched subtree
3. Catch up on the events that fired during the bootstrap
The issue is it's now very difficult to deduplicate and sanely resolve the remote state during step 3 because it's unknown whether an event arrived during the bootstrap or after. For example, imagine that between steps 1 and 2, a node /a was deleted then re-created. By the time step 3 is executed, there will be a NodeDeleted event queued up followed by a NodeCreated, causing at best a double read (one from the …
=> ZOOKEEPER-4655: Communicate the Zxid that triggered a WatchEvent to fire

zookeeper-server/src/test/java/org/apache/zookeeper/test/PersistentRecursiveWatcherTest.java
PR #1950(ZOOKEEPER-4655) was created before #1859(ZOOKEEPER-4466) merged. It changes `assertEvent`'s signature which is depended by #1859.
This fixes master compilation failure. 
cc @anmolnar @eolivelli @PapaCharlie
=> ZOOKEEPER-4655: [ADDENDUM] fix build error

.asf.yaml
=> ZOOKEEPER-4705 Restrict GitHub merge button to allow squash commit only

zookeeper-server/src/test/java/org/apache/zookeeper/test/ClientBase.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ReadOnlyModeTest.java
The same watcher was resued across different clients. It is hard to
know which event will last during verification, disconnected from old
client or connected from new client.
A brand new watcher solves this.
=> ZOOKEEPER-3996: Fix flaky ReadOnlyModeTest.testConnectionEvents

zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java
Accidentally enabled for 3.8 too when cherry-picked from master. We need to switch this off to maintain compatibility.
cc @symat
=> ZOOKEEPER-4393: [ADDENDUM] Turn off FIPS-mode by default on branch-3.8

zookeeper-server/src/main/java/org/apache/zookeeper/ZKUtil.java
Flaky test of org.apache.zookeeper.ZooKeeperTest#testDeleteRecursiveFail
We should set the flag before releasing the Semaphore.
=> ZOOKEEPER-4710 Fix ZkUtil deleteInBatch() by releasing semaphore after set flag

owaspSuppressions.xml, pom.xml
Our jackson is quite old, I want to upgrade it before release 3.8.2.
Also we have a few false positive CVEs reported by OWASP:
- CVE-2023-35116: according to jackson community, this is not a security issue, see https://github.com/FasterXML/jackson-databind/issues/3972#issuecomment-1596193098
- CVE-2022-45688: the following CVE is not even jackson related, but a vulnerability in json-java which we don't use in ZooKeeper
=> ZOOKEEPER-4716: upgrade jackson to 2.15.2, suppress two false positive CVE errors

pom.xml, zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/pom.xml, zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocketNetty.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/ClientX509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/QuorumX509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/SSLContextAndOptions.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/ZKConfig.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxnFactory.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/X509AuthenticationProvider.java, zookeeper-server/src/main/resources/lib/netty-bom-4.1.94.Final.LICENSE.txt, zookeeper-server/src/test/java/org/apache/zookeeper/test/ClientSSLTest.java
Use SslContextBuilder to create SSL context for Netty on both client and server side. This will allow users to enable OpenSSL (or other native SSL lib) support if it's installed in the OS and classpath is set up properly.
Usage guide: https://netty.io/wiki/forked-tomcat-native.html
OpenSSL support enabled on Ubuntu 20.04 looks like this:
```
2023-06-14 17:09:00,453 [myid:] - DEBUG [nioEventLoopGroup-8-1:o.a.z.c.X509Util@581] - Using Java9+ optimized cipher suites for Java version 11
2023-06-14 17:09:00,470 [myid:] - DEBUG [nioEventLoopGroup-8-1:i.n.u.i.NativeLibraryLoader@384] - Successfully loaded the library /tmp/libnetty_tcnative_linux_x86_643947969347517419998.so
2023-06-14 17:09:00,470 [myid:] - DEBUG [nioEventLoopGroup-8-1:i.n.h.s.OpenSsl@162] - Initialize netty-tcnative using …
```
=> ZOOKEEPER-4622 Add Netty-TcNative OpenSSL Support

zookeeper-server/src/main/java/org/apache/zookeeper/server/util/SerializeUtils.java
For each request, we will serialize it to a byte array.
In SerializeUtils#serializeRequest, before serializing the request, it always allocates 32 byte array. It's unnecessary; we can allocate the byte array in the catch code block.
```
public static byte[] serializeRequest(Request request) {
if (request == null || request.getHdr() == null) {
return null;
}
byte[] data = new byte[32];
try {
data = Util.marshallTxnEntry(request.getHdr(), request.getTxn(), request.getTxnDigest());
} catch (IOException e) {
LOG.error("This really should be impossible", e);
}
return data;
}
```
=> ZOOKEEPER-4718: Removing unnecessary heap memory allocation in serialization to help reduce GC pressure

zookeeper-server/src/main/java/org/apache/zookeeper/server/Request.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZKDatabase.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileTxnLog.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileTxnSnapLog.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/TxnLog.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Leader.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/util/SerializeUtils.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/TxnLogDigestTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/persistence/FileTxnLogTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/LeaderBeanTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/util/SerializeUtilsTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/LoadFromLogNoServerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/LogChopperTest.java
For each request, it will be serialized three times.
1. Leader proposal. It will serialize the request, wrap the serialized data in a proposal, then send the proposal to the quorum members.
2. SyncRequestProcessor append txn log. It will serialize the request, then write the serialized data to the txn log.
3. ZkDataBase addCommittedProposal. It will serialize the request, wrap the serialized data in a proposal, then add the proposal to committedLog.
Serialization operations are CPU-sensitive, and when the CPU experiences jitter, the time required for serialization operations will also skyrocket. Therefore, we should avoid serializing the same request multiple times.
=> ZOOKEEPER-4717: Cache serialize data in the request to avoid repeat serialize.

zookeeper-docs/src/main/resources/markdown/zookeeperMonitor.md
Documentation change only. Previous URL 404'd.
author: Jeremy Richards <jrichards@trumidtech.com>
=> Fix Grafana dashboard URL

zookeeper-docs/src/main/resources/markdown/recipes.md
The doc refers to `i` as the sequence number of node z in step 3, but in the doc, it is written as `I am`. `i` was not defined anywhere else.
Hi @eolivelli,  @kalmar, @hanm
This phrase is important to understand  this recipe. Without this update, readers would be very confused since they don't know where `i` comes from when it's referred in step 3. . Can you please review and approve?
=> Fix leader election recipe doc

.asf.yaml
will ease going to Jira issues from Git commit messages
=> GH autolink to ZOOKEEPER Jira issues

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Leader.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/LeaderBeanTest.java
When the leader tried to bind the host/IP to get connection from followers, if the DNS is not ready at first, it'll always stay in `<unresolved>` state forever. This PR tries to resolve hostname into IP each time we tried to bind.
Note: The same solution we also applied in `QuorumCnxManager` (i.e. https://github.com/apache/zookeeper/pull/1524)
https://github.com/apache/zookeeper/blob/688c69c19dc64836e91dc9ae97aeaeaf462f0556/zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumCnxManager.java#L1140
=> ZOOKEEPER-4728: force to re-resolve hostname into IP when binding.

zookeeper-server/src/test/java/org/apache/zookeeper/server/ReferenceCountedACLCacheTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/util/AdHashTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/CreateTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/MultiOperationTest.java
I am working on research that investigates test smell refactoring in which we identify alternative implementations of test cases, study how commonly used these refactorings are, and assess how acceptable they are in practice.
This smell occurs when inappropriate assertions are used, while there exist better alternatives. For example, in [CreateTest.java](https://github.com/apache/zookeeper/commit/e978917d7f72685dc684ddb26e5fa13eb2375b6d#diff-1af986ce48b5d4bb4b8e51374a70cc6e109a04c70d9f450be3df8f302010341c), I refactored `assertFalse(stat.equals(childStat));` with `assertNotEquals(stat, childStat);`.
I would like to get your feedback on this particular test smell and its refactoring. Thanks in advance for your input.
=> ZOOKEEPER-4738: Refactor assertFalse(equals()) with assertNotEquals

zookeeper-server/src/main/java/org/apache/zookeeper/server/DataTree.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/PrepRequestProcessor.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/PrepRequestProcessorTest.java
Description:
As shown in the title, see the jira link description for the background
jira: https://issues.apache.org/jira/projects/ZOOKEEPER/issues/ZOOKEEPER-4743
=> ZOOKEEPER-4743: Increase data version once more when going back to -1 from Integer.MIN_VALUE

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/src/main/java/org/apache/zookeeper/common/SSLContextAndOptions.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/X509UtilTest.java
Enable TLSv1.3 when server is running on JDK that supports it.
- Select TLSv1.3 as default protocol.
- Include both TLSv1.2 and TLSv1.3 as default enabled protocols.
- Include TLSv1.3 ciphers in default ciphers.
Fixes Jira issue https://issues.apache.org/jira/browse/ZOOKEEPER-4415
Signed-off-by: Tero Saarni <tero.saarni@est.tech>
=> ZOOKEEPER-4415: Added TLSv1.3 support to server

zookeeper-server/src/test/java/org/apache/zookeeper/test/ClientSSLTest.java
As netty-tc-native is not supported for s390x arch, there were TC failures observed in ClientSSLTest, hence skipping this TC for s390x arch only.
=> ZOOKEEPER-4739: Disable ClientSSLTest for s390x arch

zookeeper-server/src/main/java/org/apache/zookeeper/ZKUtil.java
This PR aims to pick #2020 into the `branch-3.7`.
=> ZOOKEEPER-4710 Fix ZkUtil deleteInBatch() by releasing semaphore after set flag (#2020)

zookeeper-server/src/test/java/org/apache/zookeeper/test/CheckTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/QuorumBase.java
All tests are refactored to fail before #1988 and resist more than 100 runs locally without failure after #1988.
I saw several failed ci actions due to flaky [`CheckTest::testCluster`](https://github.com/apache/zookeeper/blob/b31f776471fef79ab161f416d58367bdffaf37a9/zookeeper-server/src/test/java/org/apache/zookeeper/test/CheckTest.java#L94) after #1988 merged:
1. https://github.com/apache/zookeeper/actions/runs/6204227199/job/16879362878#step:7:767 (#2064)
2. https://github.com/apache/zookeeper/actions/runs/6211501232/job/16860755400#step:7:770 (#2065)
```
org.opentest4j.AssertionFailedError: Unable to connect to server
at org.apache.zookeeper.test.ClientBase.createClient(ClientBase.java:215)
at org.apache.zookeeper.test.ClientBase.createClient(ClientBase.java:201)
at …
```
=> ZOOKEEPER-2623: [ADDENDUM] Fix flaky CheckTest::testCluster

zookeeper-metrics-providers/zookeeper-prometheus-metrics/src/test/java/org/apache/zookeeper/metrics/prometheus/ExportJvmInfoTest.java, zookeeper-metrics-providers/zookeeper-prometheus-metrics/src/test/java/org/apache/zookeeper/metrics/prometheus/PrometheusMetricsProviderConfigTest.java, zookeeper-metrics-providers/zookeeper-prometheus-metrics/src/test/java/org/apache/zookeeper/metrics/prometheus/PrometheusMetricsProviderTest.java, zookeeper-metrics-providers/zookeeper-prometheus-metrics/src/test/java/org/apache/zookeeper/metrics/prometheus/PrometheusMetricsTestBase.java
If the `io.prometheus.client.hotspot.DefaultExports#initialize` method has been executed by other test cases before running the `org.apache.zookeeper.metrics.prometheus.ExportJvmInfoTest#exportInfo` test case, then this test case will fail.
=> ZOOKEEPER-4768: Fix flaky test org.apache.zookeeper.metrics.prometheus.ExportJvmInfoTest#exportInfo

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FastLeaderElection.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FollowerZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Learner.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/DIFFSyncTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerTestBase.java
Provides a fix for the txn loss issue caused by the race condition in DIFF sync.
=> ZOOKEEPER-4785: Txn loss due to race condition in Learner.syncWithLeader() during DIFF sync

zookeeper-server/src/test/java/org/apache/zookeeper/server/util/ConfigUtilsTest.java
Hi,
This PR adds a unit test method for a not-covered code. The method does 4 tests.
(I do it to learn how to code tests using an AI)
=> ZOOKEEPER-725: Add unit tests for ConfigUtils.getClientConfigStr

zookeeper-client/zookeeper-client-c/src/zookeeper.c, zookeeper-contrib/zookeeper-contrib-loggraph/README.md, zookeeper-docs/src/main/resources/markdown/zookeeperUseCases.md
Fix typos in docs & comments:
`zookeeper-client/zookeeper-client-c/src/zookeeper.c`
`zookeeper-contrib/zookeeper-contrib-loggraph/README.md`
`zookeeper-docs/src/main/resources/markdown/zookeeperUseCases.md`
=> Fix typos in docs & comments

zookeeper-contrib/zookeeper-contrib-zooinspector/pom.xml
There are 2 security vulnerabilities found in com.google.guava:guava 18.0
- [CVE-2018-10237](https://www.oscs1024.com/hd/CVE-2018-10237)
- [CVE-2020-8908](https://www.oscs1024.com/hd/CVE-2020-8908)
Upgrade com.google.guava:guava from 18.0 to 30.0-jre for vulnerability fix
Ideally, no insecure libs should be used.
[PR Specification](https://www.oscs1024.com/docs/pr-specification/) from OSCS
=> fix(sec): [ZooInspector] upgrade com.google.guava:guava to 30.0-jre

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md
Starting with commit https://github.com/apache/zookeeper/commit/c47ef905e077184bc5b7f555a3e2dfeb6dc046e1 the readonly mode requires local sessions to be activated.
This commit appends the related information to the docu.
In addition the impossibility to a client downgrade is noted
=> document the need for local sessions within the readonly mode

bin/zkSnapshotRecursiveSummaryToolkit.sh
When I execute the following code to analyze the snapshot file:
```
./bin/zkSnapshotRecursiveSummaryToolkit.sh /data/version-2/snapshot.c00000009 / 2 
```
Getting this error:
```
Error: Could not find or load main class 
```
I checked the source code and found that $JVMFLAGS was surrounded by quotation marks. This problem occurs when the variable $JVMFLAGS is empty.
```
"$JAVA" -cp "$CLASSPATH" "$JVMFLAGS" \
     org.apache.zookeeper.server.SnapshotRecursiveSummary "$@" 
```
The correct code should be like this
```
"$JAVA" -cp "$CLASSPATH" $JVMFLAGS \
     org.apache.zookeeper.server.SnapshotRecursiveSummary "$@"
```
=> ZOOKEEPER-4770: zkSnapshotRecursiveSummaryToolkit.sh Error: Could not find or load main class

zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxn.java, zookeeper-server/src/main/java/org/apache/zookeeper/client/ZooKeeperSaslClient.java, zookeeper-server/src/test/java/org/apache/zookeeper/SaslAuthTest.java
Move `Login` thread up one level to `SendThread`, instead of re-creating it every time a new ZooKeeperSaslClient is needed. This will avoid bombarding the KDC server with login request when the server is unavailable. It would be nice to back off in the client as well as suggested in [ZOOKEEPER-2869](https://issues.apache.org/jira/browse/ZOOKEEPER-2869).
cc @rvaleti @dbwong You guys might want to take a look.
Since we use AtomicReference for creating / destroying Login instances, this patch will resolve [ZOOKEEPER-4235](https://issues.apache.org/jira/browse/ZOOKEEPER-4235) too.
=> ZOOKEEPER-4236 Java Client SendThread create many unnecessary Login objects

zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileTxnSnapLog.java
As in the class `FileTxnSnapLog`
```java
//the directory containing
//the transaction logs
final File dataDir;
//the directory containing
//the snapshot directory
final File snapDir;
```
The `DataDir` is the one for logs. Therefore, the file path for `DataDirSize` and `LogDirSize` should be swapped.
=> ZOOKEEPER-4703: Datadir and DatalogDir size are incorrect

zookeeper-server/src/main/java/org/apache/zookeeper/Environment.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/admin/CommandsTest.java
Use jvm as the prefix for the memory env log.
=> ZOOKEEPER-4792: Use jvm as the prefix for the memory env log.

zookeeper-server/src/main/java/org/apache/zookeeper/Shell.java, zookeeper-server/src/test/java/org/apache/zookeeper/ZKUtilTest.java
Jira: https://issues.apache.org/jira/browse/ZOOKEEPER-4779
The test testUnreadableFileInput in ZKUtilTest runs fine on linux, but fails to run when running on Windows Subsystem for Linux. A simple fix to avoid failures when developing locally. The test is already skipped on windows.
=> ZOOKEEPER-4779: Fix ZKUtilTest which fails to run on WSL

zookeeper-server/src/main/java/org/apache/zookeeper/server/PurgeTxnLog.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileTxnSnapLog.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZooKeeperServerMainTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZooKeeperServerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/persistence/FileTxnSnapLogTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerTestBase.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/WatchLeakTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/Zab1_0Test.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/NonRecoverableErrorTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/RepeatStartupTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/TruncateTest.java
=> ZOOKEEPER-4730: Incorrect datadir and logdir size reported from admin and and 4lw dirs command

zookeeper-server/src/main/java/org/apache/zookeeper/server/PurgeTxnLog.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileTxnSnapLog.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZooKeeperServerMainTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZooKeeperServerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/persistence/FileTxnSnapLogTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerTestBase.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/WatchLeakTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/Zab1_0Test.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/NonRecoverableErrorTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/RepeatStartupTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/TruncateTest.java
Backport https://github.com/apache/zookeeper/pull/2043 to 3.8
=> ZOOKEEPER-4730: Incorrect datadir and logdir size reported from admin and 4lw dirs command

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FastLeaderElection.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FollowerZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Learner.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/DIFFSyncTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerTestBase.java
backporting https://github.com/apache/zookeeper/pull/2111 to branch-3.9
=> ZOOKEEPER-4785: Txn loss due to race condition in Learner.syncWithLeader() during DIFF sync (#2111)

zookeeper-docs/src/main/resources/markdown/zookeeperReconfig.md, zookeeper-server/src/main/java/org/apache/zookeeper/client/FourLetterWordMain.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/PrepRequestProcessor.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumPeer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumPeerConfig.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumPeerMain.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTLSTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerTestBase.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumServerTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/ReconfigLegacyTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ClientBase.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ReconfigTest.java
This PR addresses [ZOOKEEPER-4276](https://issues.apache.org/jira/browse/ZOOKEEPER-4276), which enables a cluster to run as a TLS-only cluster on the secureClientPort.
Previously, this was not possible due to reasons mentioned in ZOOKEEPER-4276.
In this change, we introduce a new section to `sever.X` entries of dynamic config to indicate `secureClientPort`. We also make `clientPort` section of the dynamic config as optional (previously, this was mandatory). 
For example:
```
server.5 = 125.23.63.23:1234:1235;;1237
``` 
does not have a `clientPort` and has 1237 as the `secureClientPort`.
Dev mailing list thread - https://lists.apache.org/thread/1lmqj2wonldxmk3wxbc5lvj3vsz05l7c
=> ZOOKEEPER-4276. Serving only with secureClientPort fails

zookeeper-contrib/zookeeper-contrib-huebrowser/zkui/src/zkui/templates/view.mako, zookeeper-contrib/zookeeper-contrib-monitoring/ganglia/zookeeper.pyconf, zookeeper-contrib/zookeeper-contrib-monitoring/ganglia/zookeeper_ganglia.py, zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md
`zk_followers` was renamed to `zk_learners` in 290f1fc4b907c7d51ec / [ZOOKEEPER-3117](https://issues.apache.org/jira/browse/ZOOKEEPER-3117), but many references weren't updated.
Note that the example output for `mntr` is out of date. In my Zookeeper 3.8.4 install, `mntr` produces almost 600 lines of output, not just the 15 shown. Someone more familiar with this project might want to consider reworking or removing that section.
Please let me know if there's anything else I can do to help.
=> ZOOKEEPER-4830 Replace references to zk_followers

pom.xml
Upgrade Bouncy Castle to 1.78 to address CVEs
https://bouncycastle.org/releasenotes.html#r1rv78
- https://www.cve.org/CVERecord?id=CVE-2024-29857 (reserved)
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613079
- https://www.cve.org/CVERecord?id=CVE-2024-30171 (reserved)
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6613076
- https://www.cve.org/CVERecord?id=CVE-2024-30172 (reserved)
- https://security.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-6612984
See also https://github.com/apache/pulsar/pull/22509
=> ZOOKEEPER-4827 Bump bouncycastl version from 1.75 to 1.78

pom.xml, zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/src/main/resources/LICENSE.txt, zookeeper-server/src/test/java/org/apache/zookeeper/test/ReconfigExceptionTest.java
Update slf4j to 2.x, logback to 1.3.14. This is a backward-compatible change. 
SLF4J API version 2.0.0 requires Java 8 and introduces a backward-compatible fluent logging API. By backward-compatible, we mean that existing logging frameworks do not have to be changed in order for the user to benefit from the fluent logging API.
Version 1.3.x supports Java EE, while version 1.4.x supports Jakarta EE. The two versions are feature identical.
Both 1.3.x and 1.4.x series require SLF4J 2.0.x or later.
The 1.3.x series requires Java 8 at runtime.
=> [ZOOKEEPER-4831] update slf4j from 1.x to 2.0.13, logback to 1.3.14

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FastLeaderElection.java
Fixed the incorrect order of proposedZxid and proposedEpoch in the debug statement.
=> ZOOKEEPER-4808: Fix the log statement in FastLeaderElection

zookeeper-client/zookeeper-client-c/src/mt_adaptor.c
The log callback needs to be obtained from freed zh when the log level is debug, resulting in used-after-free.
=> ZOOKEEPER-4809: Fix do_completion use-after-free when log level is debug

zookeeper-server/src/main/java/org/apache/zookeeper/server/FinalRequestProcessor.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/PrepRequestProcessor.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/Request.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/CommitProcessor.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FollowerRequestProcessor.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/ObserverRequestProcessor.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/ReadOnlyRequestProcessor.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/util/RequestPathMetricsCollector.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/CheckTest.java
Individual `OpCode.check` will get `UnimplementedException`.
JIRA: ZOOKEEPER-2623
Discussion thread: https://lists.apache.org/thread/vl816jfrklvqz29coz5qnwpom9q41pcg
This pr reworks/reverts #1988, which return an empty response for individual `OpCode.check`, for the following reasons:
* The individual `OpCode.check` is covered by `OpCode.exists`.
* In certain situation, we may want to differentiate the two(individual or not), say statistics. This could cause maintenance burden for us.
* Exposing opcode without explicit API is probably not a good.
Open this pr for easy evaluation. I will reply the discussion thread for reference.
I plan to open a draft backport on branch-3.9 to ease code review if we are willing to go this direction.
=> ZOOKEEPER-2623: [ADDENDUM] Forbid OpCode.check outside OpCode.multi

zookeeper-server/src/main/java/org/apache/zookeeper/compat/ProtocolManager.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/test/java/org/apache/zookeeper/compat/ProtocolManagerTest.java
The `ProtocolManager` class knows whether the client sent a `readOnly` flag as part of the `ConnectRequest`, and can use that information to, in turn, avoid the extra byte when serializing the `ConnectResponse`.
=> ZOOKEEPER-4814: Re-introduce support for clients incompatible with the 3.5+ `readOnly` extension

zookeeper-server/src/main/java/org/apache/zookeeper/server/Request.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/CheckTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ClientBase.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/QuorumBase.java
Individual `OpCode.check` will get `UnimplementedException`.
This is a squashed backport of several commits from master:
1. b31f776471fef79ab161f416d58367bdffaf37a9 (#1988)
2. dc99bd75fe495c9ef2718fb1a10e175a23fb38d4 (#2067)
3. 66f9cc3941f09ca00464760c78e30b97bd7c1faa (#2104)
=> Backport to branch-3.8: ZOOKEEPER-2623: Forbid OpCode.check outside OpCode.multi

zookeeper-server/src/main/java/org/apache/zookeeper/cli/Base64OutputFormatter.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/CliCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/CommandUsageHelper.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/GetCommand.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/HexDumpOutputFormatter.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/OutputFormatter.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/PlainOutputFormatter.java, zookeeper-server/src/main/java/org/apache/zookeeper/cli/SetCommand.java
Currently, the `get` and `set` commands in the zkCli tool only support reading and writing text data. However, znode data can be an arbitrary byte array. It would be useful to read and write binary data in `base64` or `hexdump` format.
This PR provides two options for the `get` command:
- `get -b /foo`: Outputs data in base64 format.
- `get -x /foo`: Outputs data in hexdump format.
Additionally, it provides a `-b` option for the `set` command to allow users to set binary data in `base64` format for a znode. For instance: `set -b /foo em9va2VlcGVy`.
=> ZOOKEEPER-4850: Enhance zkCli Tool to Support Reading and Writing Binary Data

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxnFactory.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/ProviderRegistry.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ClientSSLReloadTest.java
This is cherry-pick from #1839. This PR is the same as the #1839 on the master branch, only changing the documentation about the version numbers.
Signed-off-by: Li Wang <li4wang@gmail.com>
=> ZOOKEEPER-4546: Backport auto reloading client key/trust store to 3.8

zookeeper-server/src/main/java/org/apache/zookeeper/ZooKeeper.java, zookeeper-server/src/test/java/org/apache/zookeeper/ZKTestCase.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/EagerACLFilterTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumRequestPipelineTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/QuorumTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/SessionTest.java
Previously, there is no synchronous `sync` so client has to convert asynchronous `sync` a bit to fit synchronous call chains. This is apparently unfriendly.
Besides above, in absent of ZOOKEEPER-22, we can't issue a fire and forget asynchronous `sync` to gain strong consistent. So it becomes crucial for client to have a convenient synchronous `sync`.
Refs: ZOOKEEPER-1167, ZOOKEEPER-4747
=> ZOOKEEPER-4747: Add synchronous sync to ease synchronous call chains

zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileTxnLog.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/persistence/FileTxnLogTest.java
When a new txn log is created, it encounters a failure before writing to the file header. The txn log file is empty at this moment, the server starts up again, reads the file, and fails to load the database because the header is not recognized.
The patch detects that the empty txn log is at the end of the database, and if the file is empty, it deletes the file and prompts the server to reboot to reload it.
When one of the txn logs in the middle of the database is empty, it will refuse to start up since it's a real corruption.
=> ZOOKEEPER-2332: Fix server failed to start for empty txn log

zookeeper-assembly/pom.xml, zookeeper-contrib/zookeeper-contrib-zooinspector/pom.xml, zookeeper-server/pom.xml
Java libraries should not have `runtime` dependencies on logging backends, since they are often included in third-party applications that might make a different choice of backend.
This PR:
* removes the Logback dependency from the runtime scope of the `zookeeper` artifact and moves it into the `test` Maven scope,
* adds Logback to `zookeeper-assembly`, which is used to produce the standalone [binary distribution](https://zookeeper.apache.org/releases) available on Zookeeper's site.
=> [ZOOKEEPER-4820] Fix propagation of Logback dependencies

zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FollowerZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Learner.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/Zab1_0Test.java
This fix aims to fix a bunch of issues in follower's syncWithLeader(). 
e.g.,
[ZOOKEEPER-4394](https://issues.apache.org/jira/browse/ZOOKEEPER-4394): NullPointerException when follower receives COMMIT after replying NEWLEADER ack in syncWithLeader().
Explanation: In syncWithLeader(), a follower may receive the COMMIT message after replying NEWLEADER ack. e.g., a follower receives the following messages in order:
DIFF -> PROPOSAL -> COMMIT -> _PROPOSAL_ -> NEWLEADER -> _COMMIT_ -> UPTODATE
NullPointerException will occur  if the corresponding _PROPOSAL_ has been processed and removed from the "packetsNotCommitted" during the follower process NEWLEADER.
To fix this, when the follower receives NEWLEADER, it does the following things in order:
1. take snapshot if needed;
2. persist and …
=> ZOOKEEPER-4394: Apply only committed requests in sync with leader before NEWLEADER ACK

pom.xml, zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocketNetty.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/UnifiedServerSocket.java
Check for failed/cancelled ChannelFutures before acquiring connectLock. This prevents lock contention where cleanup is unable to complete.
Replaces #1713 (target `master` rather than `branch-3.5`)
=> ZOOKEEPER-4293: Lock Contention in ClientCnxnSocketNetty

zookeeper-jute/src/main/java/org/apache/jute/BinaryInputArchive.java, zookeeper-jute/src/test/java/org/apache/jute/BinaryInputArchiveTest.java
This jira is related to ZOOKEEPER-3496: Transaction larger than jute.maxbuffer makes ZooKeeper service unavailable
=> ZOOKEEPER-4843: Encountering an 'Unreasonable Length' error when configuring jute.maxbuffer to 1GB or more

zookeeper-server/src/main/java/org/apache/zookeeper/server/ZKDatabase.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServerMain.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/FileTxnSnapLog.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/LeaderZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Learner.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/LearnerZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/ObserverZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/ReadOnlyZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/SendAckRequestProcessor.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZooKeeperServerShutdownTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/WatchLeakTest.java
This PR fixes the shutdown errors that were added in #157, and also avoids a common NPE during ZK shutdown from a learner, when the leader shuts down (first commit).
Together with #2111 and #2152, this should cover all the fixes in #1925. 
We've had the forked ZK from #1925 running embedded in hundreds, if not thousands, of ZK clusters, with rolling restarts most days, and we've had zero cases of inconsistent data since we patched—one or a few cases per week before that.
(We still sometimes see ephemeral nodes remain after the leader is brutally taken down, i.e., with `Runtime.halt()`, but this looks different; it seems clearing out client sessions, and their ephemeral nodes, simply isn't done when death is too sudden.)
=> ZOOKEEPER-4712: Fix partially shutdown of ZooKeeperServer and its processors

zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxn.java, zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocket.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ReconfigTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/SessionTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/SessionTimeoutTest.java
ZooKeeper session will expire approximately after negotiated session timeout. Currently, client will learn this after successful contact to ZooKeeper cluster. This exposes an endless client side connection loss when client can't reach ZooKeeper cluster due to either incomplete connection string or whole cluster downtime.
This pr proposes to introduce a client side session expiration timeout to deal with this. The client side timeout will be approximately `4/3` of server side counterpart, so it can tolerate small skew.
At least four jira issues reported the behavior.
* ZOOKEEPER-2188: client connection hung up because of dead loop
* ZOOKEEPER-4412: client blocked too long before session timeout
* ZOOKEEPER-4508: ZooKeeper client run to endless loop in ClientCnxn.SendThread.run if all …
=> ZOOKEEPER-4508: Expire session in client side to avoid endless connection loss

zookeeper-server/src/main/java/org/apache/zookeeper/Login.java, zookeeper-server/src/main/java/org/apache/zookeeper/client/ZooKeeperSaslClient.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ServerCnxnFactory.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperSaslServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/SaslServerCallbackHandler.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/auth/SaslQuorumAuthLearner.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/auth/SaslQuorumAuthServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/auth/SaslQuorumServerCallbackHandler.java, zookeeper-server/src/test/java/org/apache/zookeeper/KerberosTicketRenewalTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/SaslAuthRequiredMultiClientTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/SaslTestUtil.java
Currently If a non-existent username is currently used along with the password of the last successfully logged-in user, this non-existent user can successfully log in. This issue occurs because the SaslServerCallbackHandler does not clear the information of the previously successfully logged-in user when the username does not exist. This Pull Request resolves this issue.
Assoiated jira issue: [ZOOKEEPER-4839](https://issues.apache.org/jira/projects/ZOOKEEPER/issues/ZOOKEEPER-4839?filter=recentlyviewed&orderby=created+DESC%2C+lastViewed+DESC)
=> ZOOKEEPER-4839: Fix SASL DIGEST-MD5 authenticated with last successfully logined username

pom.xml
=> ZOOKEEPER-4868. Bump commons-io to resolve CVE

zookeeper-server/src/main/java/org/apache/zookeeper/server/persistence/TxnLogToolkit.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/persistence/TxnLogToolkitTest.java
Currently, the TxnLogToolkit only decodes error transactions to recognized strings. This PR seeks to enhance the toolkit to decode other types of transactions into a better format.
Associated jira issue [ZOOKEEPER-4864](https://issues.apache.org/jira/browse/ZOOKEEPER-4864)
=> ZOOKEEPER-4864: Fix bad format when dump MultiTxn in TxnLogToolkit

zookeeper-client/zookeeper-client-c/src/zookeeper.c
When the user calls ZOOAPI zoo_set_servers() and free zh->hostname, resulting in use-after-free in zookeeper_interest().
=> ZOOKEEPER-4699: Fix hostname use-after-free in the C client

zookeeper-server/src/main/java/org/apache/zookeeper/server/ByteBufferRequestRecord.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/Request.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/RequestRecord.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/SimpleRequestRecord.java
Fix Apache License Header Formatting in Java Files
Description
This pull request addresses a minor documentation formatting issue within the Apache License headers across several Java files. Specifically, the license header contained an incorrect *uuuuu mark, which affected readability and consistency. This update ensures the license header aligns with the official Apache License format.
Changes Made
Corrected the erroneous *uuuuu entry in the license header to reflect the standard Apache License text.
Verified formatting across affected files to maintain consistency.
Files Updated
Updated four Java files under the org.apache.zookeeper.server package.
Why This Change is Needed
Ensuring the license header follows the standard format improves code readability and maintains compliance with …
=> ZOOKEEPER-4852: Fix the bad "*uuuuu" mark in the ASF license

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/ZKConfig.java
FIPS mode _technically_ covers this, in a sort of sledgehammery way, but I think it's still worthwhile to have an explicit option for this and only this. Especially since FIPS compliance is a pretty broad thing (see [ZOOKEEPER-4832](https://issues.apache.org/jira/browse/ZOOKEEPER-4832)) that will likely expand in the future to cover a lot of things that may or may not be desired.
=> ZOOKEEPER-4790: Make client hostname verification configurable

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md
=> ZOOKEEPER-4889: Fallback to DIGEST-MD5 auth mech should be disabled in Fips mode - doc change  (ADDENDUM)

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/src/main/java/org/apache/zookeeper/client/ZooKeeperSaslClient.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/X509AuthenticationProvider.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/auth/SaslQuorumAuthLearner.java, zookeeper-server/src/main/java/org/apache/zookeeper/util/SecurityUtils.java
Backported from #2213 and #2214
=> ZOOKEEPER-4889: Fallback to DIGEST-MD5 auth mech should be disabled in Fips mode (branch-3.8)

.github/workflows/ci.yaml, .github/workflows/e2e.yaml, .github/workflows/manual.yaml
* Use v4 actions
* Use language-specific setup-java's cache instead of general purpose actions/cache
=> [CI] (Trivial) Update GitHub Actions

zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/admin/Commands.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZookeeperServerRestoreTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZookeeperServerSnapshotTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/admin/RestoreQuorumTest.java
=> ZOOKEEPER-4872:  SnapshotCommand should not perform fastForwardFromEdits

zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxn.java, zookeeper-server/src/main/java/org/apache/zookeeper/client/FourLetterWordMain.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ReadOnlyModeWithSSLTest.java
ClientCnxn::pingRwServer uses raw socket to issue "isro" 4lw command. This results in unsuccessful handshake to tls server. Use SSLSocket when zookeeper.client.secure is set to true.
associated jira issue [ZOOKEEPER-4819](https://issues.apache.org/jira/browse/ZOOKEEPER-4819)
=> ZOOKEEPER-4819 Fix can't seek for writable tls server if connected to readonly server

zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java
fix log arguments typo, exception stack does not need placeholder.
https://issues.apache.org/jira/browse/ZOOKEEPER-4879
=> ZOOKEEPER-4879: Fix log arguments typo

zookeeper-jute/src/main/java/org/apache/jute/compiler/JField.java, zookeeper-jute/src/main/java/org/apache/jute/compiler/JRecord.java, zookeeper-jute/src/main/java/org/apache/jute/compiler/generated/rcc.jj, zookeeper-jute/src/test/java/org/apache/jute/compiler/JRecordTest.java
Generate comments from zookeeper.jute into code: https://issues.apache.org/jira/browse/ZOOKEEPER-4880
Support generating end-of-line comments and class comments in `zookeeper.jute` into code.
1. By comparing the `zookeeper-jute/target/generated-sources/java/org/apache/zookeeper` and `zookeeper-client/zookeeper-client-c/generated` directories before and after the modification, there are no other differences except the comments.
<br>
<br>
2. When the test class has multiple lines of comments, the comments can be generated normally.
<br>
<br>
3. Testing vector type properties can generate comments normally.
<br>
<br>
4. Testing class type properties can generate comments normally
<br>
<br>
5. Testing comments that do not meet expectations will not generate comments and will not affect the …
=> ZOOKEEPER-4880: Generate comments from zookeeper.jute into code.

zookeeper-client/zookeeper-client-c/src/zookeeper.c
Fixing memory leak by freeing memory allocated by strdup in cert_t.
=> ZOOKEEPER-4020: Fix memory leak from ssl cert in c client

zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java
=> ZOOKEEPER-4858: Remove the lock contention between snapshotting and the sync operation

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumPeer.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumPeerMainTest.java
```
org.opentest4j.AssertionFailedError: create /zk2 should have failed
at org.apache.zookeeper.server.quorum.QuorumPeerMainTest.testFailedTxnAsPartOfQuorumLoss(QuorumPeerMainTest.java:762)
```
The test starts other members before the `create` operation. This causes
the old leader rejoin with them to form quorum.
This pr moves starting of stopped members after `create`.
=> ZOOKEEPER-3624: Fix flaky `QuorumPeerMainTest::testFailedTxnAsPartOfQuorumLoss`

zookeeper-server/src/main/java/org/apache/zookeeper/server/DataTree.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/DataTreeTest.java
In the scenario when ZooKeeper restore from fuzzy snapshot, there's possibility that we have a znode in the snapshot, but the attached ACL is missing from the ACL cache. In this case ZK will fast forward to znode's createTxn and replays it. While we skip re-creating the existing znode, we have a chance to fix the potentially wrong ACL reference.
=> ZOOKEEPER-4846 Failure to reload database due to missing ACL

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FastLeaderElection.java
WorkerSender inherits from ZooKeeperThread. When using WorkerSender, a WorkerSender thread is created first, followed by the creation of a new thread where WorkerSender is passed as a task. At this point, the ExceptionHandler in ZooKeeperThread does not take effect.
=> ZOOKEEPER-4898: FastLeaderElection WorkerSender/WorkerReceiver don't need to be Thread

zookeeper-server/src/main/java/org/apache/zookeeper/audit/AuditHelper.java, zookeeper-server/src/test/java/org/apache/zookeeper/audit/Slf4JAuditLoggerTest.java
Without this, `AuditHelper.addAuditLog` ignores the `createTTL` opcode outside of `multi` transactions, resulting in missing audit log entries.
=> ZOOKEEPER-4725: Record TTL node creations in audit log

zookeeper-server/src/main/java/org/apache/zookeeper/server/NettyServerCnxn.java
Refer to [ZOOKEEPER-4907](https://issues.apache.org/jira/browse/ZOOKEEPER-4907)
We got the error:
2024-11-07 19:03:01,414 [myid:14] - WARN [nioEventLoopGroup-7-25:NettyServerCnxn@537] - Closing connection to /135.224.186.250:47051
java.io.IOException: **Len error** 794913900
at org.apache.zookeeper.server.NettyServerCnxn.receiveMessage(NettyServerCnxn.java:521)
at org.apache.zookeeper.server.NettyServerCnxn.processMessage(NettyServerCnxn.java:374)
at org.apache.zookeeper.server.NettyServerCnxnFactory$CnxnChannelHandler.channelRead(NettyServerCnxnFactory.java:357)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
at …
=> ZOOKEEPER-4907: Stop client packets processing after server channel closed

zookeeper-client/zookeeper-client-c/tests/zkServer.sh
A fixup to #2224, see https://github.com/apache/zookeeper/pull/2224#issuecomment-2764519504.
=> ZOOKEEPER-3766: [ADDENDUM] Fix TestSASLAuth failure

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumCnxManager.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/auth/QuorumAuthObserverTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/auth/QuorumAuthTestBase.java
ZK BUG Like QuorumAuthObserverTest#testSmallObserverJoinSASLQuorum
When SASL Quorum like:
server.11=localhost:11223:11224:participant
server.21=localhost:11226:11227:participant
server.1=localhost:11229:11230:observer
The server.1 can't join quorum.
=> ZOOKEEPER-4886: Fix observer with small myid can't join SASL quorum

zookeeper-server/src/test/java/org/apache/zookeeper/server/ZooKeeperServerMaxCnxnsTest.java
The restriction of maxCnxns may not be accurate due to concurrent races, say concurrent accepting. This is totally fine and not worth to make it accurate due to possible negative effects.
This commit circumvents this by connecting to each server maxCnxns times.
=> ZOOKEEPER-4920: Fix flaky test ZooKeeperServerMaxCnxnsTest

zookeeper-server/src/main/java/org/apache/zookeeper/common/Time.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/DatadirCleanupManager.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumPeerConfig.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/TimeTest.java
`QuorumPeerConfig` is marked public with `@InterfaceAudience.Public`. Though, I don't think there are much chances for `getPurgeInterval` to be used. But let's keep our promise.
Backward Compatibility: https://cwiki.apache.org/confluence/pages/viewpage.action?pageId=25200595#ReleaseManagement-BackwardCompatibility
=> ZOOKEEPER-4829: [ADDENDUM] Improve backward compatibility for QuorumPeerConfig::getPurgeInterval with 3.9

zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxn.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/SessionTimeoutTest.java
This partially rollback ZOOKEEPER-4508 to keep consistent with versions prior to 3.9.3 (excluded), so to maintain compatibility with third party libraries.
Refs: ZOOKEEPER-4508, ZOOKEEPER-4921, ZOOKEEPER-4923 and https://lists.apache.org/thread/nfb9z7rhgglbjzfxvg4z2m3pks53b3c1
=> ZOOKEEPER-4921: Retry endlessly to establish a brand-new session

zookeeper-client/zookeeper-client-c/src/zookeeper.c
c->c is a union so setting c.acl_result would override c.string_stat_result.
However, since they're all function pointers pointing to the same function, this won't cause any issue as c.string_stat_result is still correct. This might cause issue if we change the type of these completions in the future.
This also makes the code consistent.
=> ZOOKEEPER-4604: Fix missing break in switch branch COMPLETION_STRING_STAT

zookeeper-server/src/main/java/org/apache/zookeeper/server/DataTree.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ServerMetrics.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/CreateTTLTest.java
=> ZOOKEEPER-4930: Add metrics for TTL node deletion

zookeeper-server/src/main/java/org/apache/zookeeper/ZooKeeper.java, zookeeper-server/src/main/java/org/apache/zookeeper/client/ZooKeeperBuilder.java, zookeeper-server/src/main/java/org/apache/zookeeper/client/ZooKeeperOptions.java, zookeeper-server/src/test/java/org/apache/zookeeper/client/ZooKeeperBuilderTest.java
`ZooKeeperBuilder` is introduced in ZOOKEEPER-4697 which targets 3.10.0, so this api change breaks nothing.
Refs: ZOOKEEPER-4697, ZOOKEEPER-4943
=> ZOOKEEPER-4943: Use Duration for session timeout in ZooKeeperBuilder

zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FastLeaderElection.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/QuorumCnxManager.java
JIRA:https://issues.apache.org/jira/browse/ZOOKEEPER-4787
=> ZOOKEEPER-4787: Fix quorum join failure due to inconsistent wire message charset during leader election

pom.xml, zookeeper-server/src/main/java/org/apache/zookeeper/ClientCnxnSocketNetty.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/UnifiedServerSocket.java
I'd like to upgrade Netty to **4.1.119.Final** version on `branch-3.8` in two steps. This is the first patch to backport, unfortunately, due to code deprecation in Netty, there's no other way to upgrade.
Interesting that license files are missing from this commit, but looks like it was fixed in the second patch that I'm going to backport.
=> ZOOKEEPER-4293. Lock Contention in ClientCnxnSocketNetty (possible deadlock) (branch-3.8 backport)

owaspSuppressions.xml
Based on [ZOOKEEPER-4876](https://issues.apache.org/jira/browse/ZOOKEEPER-4876) ZooKeeper is not affected by this CVE, but we have removed it from Owasp suppressions for some reason. Accidentally...?
I put it back in this patch for all active branches.
=> ZOOKEEPER-4932 The newest version of zookeeper includes Jetty versiob 9.4.57.x which has CVE-2024-6763 issue

zookeeper-contrib/zookeeper-contrib-zooinspector/src/main/java/org/apache/zookeeper/inspector/manager/ZooInspectorManager.java, zookeeper-docs/src/main/resources/markdown/zookeeperProgrammers.md, zookeeper-server/src/test/java/org/apache/zookeeper/ZooKeeperTest.java
There are typo errors in Programmers Guide in the documentation of zookeeper 3.9.3.
=> ZOOKEEPER-4953:  Fix typos for word ZooKeeper from ZooKeeeper

zookeeper-server/src/main/java/org/apache/zookeeper/server/Request.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/TxnLogEntry.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZKDatabase.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/ZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Follower.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/FollowerZooKeeperServer.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Learner.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/quorum/Observer.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/TxnLogDigestTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ZxidRolloverTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumSyncTest.java
There are two variants of `ZooKeeperServer::processTxn`. Those two variants diverge significantly since ZOOKEEPER-3484. `processTxn(Request request)` pops outstanding change from `outstandingChanges` and adds txn to `committedLog` for follower to sync in addition to what `processTxn(TxnHeader hdr, Record txn)` does. The `Learner` uses `processTxn(TxnHeader hdr, Record txn)` to commit txn to memory after ZOOKEEPER-4394, which means it leaves `committedLog` untouched in `SYNCHRONIZATION` phase.
This way, a stale follower will have hole in its `committedLog` after joining cluster. The stale follower will propagate the in memory hole to other stale nodes after becoming leader. This causes data loss.
The test case fails on master and 3.9.3, and passes on 3.9.2. So only 3.9.3 is affected.
This …
=> ZOOKEEPER-4925: Fix data loss due to propagation of discontinuous committedLog

pom.xml
Attempt to upgrade logback and slf4j on branch-3.9
=> ZOOKEEPER-4891. Update logback to 1.3.15 to fix CVE-2024-12798. (branch-3.9)

zookeeper-docs/src/main/resources/markdown/zookeeperAdmin.md, zookeeper-server/src/main/java/org/apache/zookeeper/common/ClientX509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/common/X509Util.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/X509AuthenticationProvider.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/X509TestContext.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/X509TestHelpers.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/X509UtilTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ClientSSLRevocationTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/quorum/QuorumSSLTest.java
Refs: ZOOKEEPER-4955, apache/zookeeper#2289, stoty/zookeeper#2
=> ZOOKEEPER-4955: Fix intererence with jvm wide ssl properties for ssl.crl and ssl.ocsp

zookeeper-server/src/main/java/org/apache/zookeeper/server/auth/IPAuthenticationProvider.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/auth/IPAuthenticationProviderTest.java, zookeeper-server/src/test/java/org/apache/zookeeper/test/ACLTest.java
With this change the IPAuthenticationProvider class will handle the IPV6 addresses properly. It will now perform validation of IPV6 addresses, will convert it into a byte array taking into consideration the IPv6 segments, format.
=> ZOOKEEPER-4240: Add IPV6 support for ZooKeeper ACL

zookeeper-docs/src/main/resources/markdown/releasenotes.md
This pr targets branch-3.9 as I saw #2296 is also targeting at that branch. Please adjust it if it does not meet your release procedure.
Feel free to adjust the sentences if they are not fluent in reading.
=> Note breaking change for slf4j-api and logback-classic upgrade

zookeeper-server/src/test/java/org/apache/zookeeper/common/ssl/Ca.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/ssl/Cert.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/ssl/CertSigner.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/ssl/OCSPHandler.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/ssl/PemFile.java, zookeeper-server/src/test/java/org/apache/zookeeper/common/ssl/X509CertBuilder.java, zookeeper-server/src/test/java/org/apache/zookeeper/server/ClientSSLRevocationTest.java
This is a fixup commit to #2292. It contains only test code changes to make SSL related classes, e.g. Ca, Cert and etcd., to be reusable.
=> ZOOKEEPER-4955: [ADDENDUM] Refactor Ca, Cert and etc. so to be reusable

zookeeper-metrics-providers/zookeeper-prometheus-metrics/src/main/java/org/apache/zookeeper/metrics/prometheus/PrometheusMetricsProvider.java, zookeeper-server/src/main/java/org/apache/zookeeper/server/RateLogger.java
Implemented `PrometheusRejectedExecutionHandler` and override the `rejectedExecution()` API to fix the large memory footprint and long GC pause of RejectedExecutionException handler.  No more RejectedExecutionException() will be thrown.
This enhancement increased read throughput by 140% according to our perf comparison tests result.
=> ZOOKEEPER-4952:Reduce the GC overhead of Prometheus reject exception handling

zookeeper-metrics-providers/zookeeper-prometheus-metrics/pom.xml, zookeeper-metrics-providers/zookeeper-prometheus-metrics/src/main/java/org/apache/zookeeper/metrics/prometheus/PrometheusMetricsProvider.java, zookeeper-metrics-providers/zookeeper-prometheus-metrics/src/test/java/org/apache/zookeeper/metrics/prometheus/PrometheusMetricsProviderConfigTest.java
Those tests use hard written ports to listen.
```
org.apache.zookeeper.metrics.MetricsProviderLifeCycleException: java.io.IOException: Failed to bind to /0.0.0.0:50512
at org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProvider.start(PrometheusMetricsProvider.java:213)
at org.apache.zookeeper.metrics.prometheus.PrometheusMetricsProviderConfigTest.testValidHttpsAndHttpConfig(PrometheusMetricsProviderConfigTest.java:88)
```
=> ZOOKEEPER-4972: Fix flaky tests in PrometheusMetricsProviderConfigTest

pom.xml
Authentication is now required for **Sonatype OSS Index**: https://ossindex.sonatype.org/doc/auth-required
I don't think we need this feature, so I won't add API key to the public repo, but I have to update the plugin to skip indexing with softfail.
=> ZOOKEEPER-4984: Upgrade OWASP plugin to 12.1.6 due to breaking changes in the API
